// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using ItemSense;
using System.Text;
using Newtonsoft.Json.Converters;

public enum ReaderType
{
	XARRAY = 0,
	SPEEDWAY = 1,
}

namespace ItemSense
{
    public class ReaderDefinition
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("address")]
        public string Address { get; set; }

        [JsonProperty("type")]
        [JsonConverter(typeof(StringEnumConverter))]
        public ReaderType Type { get; set; }

        [JsonProperty("placement")]
        public Placement Placement { get; set; }

        [JsonProperty("facility")]
        public string Facility { get; set; }

        [JsonProperty("readerZone")]
        public string ReaderZone { get; set; }

        [JsonProperty("antennaZones")]
        public Dictionary<int, string>[] AntennaZone { get; set; }
    }

    public class Placement
    {
        [JsonProperty("x")]
        public float X { get; set; }

        [JsonProperty("y")]
        public float Y { get; set; }

        [JsonProperty("z")]
        public float Z { get; set; }

        [JsonProperty("yaw")]
        public float Yaw { get; set; }

        [JsonProperty("pitch")]
        public float Pitch { get; set; }

        [JsonProperty("roll")]
        public float Roll { get; set; }
    }
}
