// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ItemSense
{
    internal class ZoneTransitionMessageQueueConfig
    {
        [JsonProperty("fromZone")]
        public string FromZone { get; set; }

        [JsonProperty("toZone")]
        public string ToZone { get; set; }

        [JsonProperty("epc", NullValueHandling=NullValueHandling.Ignore)]
        public string EPC { get; set; }
    }
}
