// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ItemSense
{
    internal class Items
    {
        [JsonProperty("items")]
        //public Item[] ItemArray { get; set; }
        public List<ItemSense.Item> ItemList { get; set; }

        [JsonProperty("nextPageMarker")]
        public string NextPageMarker { get; set; }
    }

}
