// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ItemSense
{
    internal class Item
    {
        [JsonProperty("epc")]
        public string Epc { get; set; }

        [JsonProperty("tagId")]
        public string TagId { get; set; }

        [JsonProperty("xLocation")]
        public double XLocation { get; set; }

        [JsonProperty("yLocation")]
        public double YLocation { get; set; }

        [JsonProperty("zLocation")]
        public double ZLocation { get; set; }

        [JsonProperty("zone")]
        public string Zone { get; set; }

        [JsonProperty("facility")]
        public string Facility { get; set; }

        [JsonProperty("presenceConfidence")]
        public string PresenceConfidence { get; set; }

        [JsonProperty("lastModifiedTime")]
        public string LastModifiedTime { get; set; }

        public string itemToCsvString()
        {
            return string.Format(
                "{0},{1},{2},{3},{4},{5},{6},{7},{8}",
                Epc,
                TagId,
                XLocation,
                YLocation,
                ZLocation,
                Zone,
                Facility,
                PresenceConfidence,
                LastModifiedTime
                );
        }
    }
}
