// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ItemSense
{
    internal class Job
    {
        [JsonProperty("recipeName")]
        public string RecipeName { get; set; }

        [JsonProperty("durationSeconds")]
        public int DurationSeconds { get; set; }

        [JsonProperty("playbackLoggingEnabled", NullValueHandling=NullValueHandling.Ignore)]
        public bool? PlaybackLoggingEnabled { get; set; }

        [JsonProperty("presenceLoggingEnabled", NullValueHandling=NullValueHandling.Ignore)]
        public bool? PresenceLoggingEnabled { get; set; }

        [JsonProperty("startDelay", NullValueHandling=NullValueHandling.Ignore)]
        public int? StartDelay { get; set; }

        [JsonProperty("reportToDatabaseEnabled", NullValueHandling=NullValueHandling.Ignore)]
        public bool ReportToDatabaseEnabled { get; set; }

        [JsonProperty("reportToMessageQueueEnabled", NullValueHandling=NullValueHandling.Ignore)]
        public bool ReportToMessageQueueEnabled { get; set; }

        [JsonProperty("reportToFileEnabled", NullValueHandling=NullValueHandling.Ignore)]
        public bool? ReportToFileEnabled { get; set; }

        [JsonProperty("facility", NullValueHandling=NullValueHandling.Ignore)]
        public string Facility { get; set; }
    }
}
